version: '3'
services:
  CustomerMS:
    image: ghcr.io/stuntman1988/customerms:latest
    ports:
      - "8081:8080"
    restart: always

    environment:
      MYSQL_HOST: customer-mysql
      DB_USER: customeruser
      DB_PASSWORD: Password
      MYSQL_PORT: 3306
      DB_DATABASE: Customer_Database
    depends_on:
      - customer-mysql

  customer-mysql:
    container_name: customer-mysql
    image: mysql:latest
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: Customer_Database
      MYSQL_USER: customeruser
      MYSQL_PASSWORD: Password
      MYSQL_RANDOM_ROOT_PASSWORD: yes

  PurchaseMS:
    image: demo/purchasems
    ports:
      - "8082:8080"
    restart: always

    environment:
      MYSQL_HOST: purchase-mysql
      DB_USER: purchaseuser
      DB_PASSWORD: Password
      MYSQL_PORT: 3306
      DB_DATABASE: Purchase_Database
    depends_on:
      - purchase-mysql

  purchase-mysql:
    container_name: purchase-mysql
    image: mysql:latest
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: Purchase_Database
      MYSQL_USER: purchaseuser
      MYSQL_PASSWORD: Password
      MYSQL_RANDOM_ROOT_PASSWORD: yes


  ItemMS:
      image: demo/itemms
      ports:
        - "8083:8080"
      restart: always

      environment:
        MYSQL_HOST: item-mysql
        DB_USER: itemuser
        DB_PASSWORD: Password
        MYSQL_PORT: 3306
        DB_DATABASE: Item_Database
      depends_on:
        - item-mysql

  item-mysql:
    container_name: item-mysql
    image: mysql:latest
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: Item_Database
      MYSQL_USER: itemuser
      MYSQL_PASSWORD: Password
      MYSQL_RANDOM_ROOT_PASSWORD: yes
