version: '3'
services:
  user-service:
    image: your-user-service-image:tag
    ports:
      - 8081:8080
  purchase-service:
    image: your-purchase-service-image:tag
    ports:
      - 8082:8080
  product-service:
    image: your-product-service-image:tag
    ports:
      - 8083:8080