version: '3'
services:
  CustomerMS:
    image: demo/customerms
    ports:
      - 8081:8080
    environment:
      MYSQL_HOST: customer-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      MYSQL_DB: Customer_Database
      depends_on:
        -customer-mysql

  customer-mysql:
    container_name: customer-mysql
    image: mysql:latest
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: Customer_Database
      MYSQL_ROOT_PASSWORD: root

  PurchaseMS:
    image: demo/purchasems
    ports:
      - 8082:8080
    environment:
      MYSQL_HOST: purchase-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      MYSQL_DB: Purchase_Database
      depends_on:
        -purchase-mysql

  purchase-mysql:
    container_name: purchase-mysql
    image: mysql:latest
    ports:
      - 3311:3306
    environment:
      MYSQL_DATABASE: Purchase_Database
      MYSQL_ROOT_PASSWORD: root


  ItemMS:
      image: demo/itemms
      ports:
        - 8083:8080
      environment:
        MYSQL_HOST: item-mysql
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_PORT: 3306
        MYSQL_DB: Item_Database
        depends_on:
          -item-mysql
  item-mysql:
    container_name: item-mysql
    image: mysql:latest
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: Item_Database
      MYSQL_ROOT_PASSWORD: root
